/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IERC2981__factory } from "./IERC2981__factory";
export { IERC4906__factory } from "./IERC4906__factory";
export { IERC5267__factory } from "./IERC5267__factory";
export { IERC5805__factory } from "./IERC5805__factory";
export { IERC6372__factory } from "./IERC6372__factory";
